// ==================== GALÁXIA 1 — Alpha ====================
// Banco: 40 questões M1 + 40 questões M2 + 40 questões M3
// Sorteio: 10 de M1 + 15 de M2 + 15 de M3 = 40 por tentativa
// Aprovação: 28/40 (70%)
// Sem avanço forçado — erra, recebe tip, fica na questão

const GALAXY_1 = {
    id: 1,
    name: 'Galáxia Alpha',
    requiredWorld: 3,
    totalQuestions: 40,
    passingScore: 28,

    // ===== BLOCO M1 — Variáveis e Tipos (40 questões) =====
    bankM1: [
        { id: 'm1_01', type: 'multiple',
          question: 'Qual é o tipo correto para armazenar o nome de um aluno?',
          options: ['Texto', 'Inteiro', 'Real', 'Lógico'],
          correct: 0,
          tip: 'Nomes são sequências de caracteres — use Texto.' },

        { id: 'm1_02', type: 'multiple',
          question: 'Uma variável recebe o valor 3.14. Qual é o tipo mais adequado?',
          options: ['Real', 'Inteiro', 'Texto', 'Lógico'],
          correct: 0,
          tip: 'Números com casas decimais são do tipo Real.' },

        { id: 'm1_03', type: 'multiple',
          question: 'O que acontece quando você tenta somar um Inteiro com um Texto?',
          options: ['Erro de tipo', 'Retorna o número', 'Retorna o texto', 'Retorna zero'],
          correct: 0,
          tip: 'Tipos incompatíveis causam erro — você não pode somar 5 com "olá".' },

        { id: 'm1_04', type: 'multiple',
          question: 'Qual dessas atribuições está correta em pseudocódigo?',
          options: ['idade ← 25', '25 ← idade', 'idade == 25', 'inteiro ← idade'],
          correct: 0,
          tip: 'A seta ← aponta da direita para a esquerda: variável recebe valor.' },

        { id: 'm1_05', type: 'multiple',
          question: 'Uma variável do tipo Lógico pode armazenar:',
          options: ['verdadeiro ou falso', 'qualquer número', 'texto ou número', 'apenas 0 ou 1'],
          correct: 0,
          tip: 'Lógico representa apenas dois estados: verdadeiro ou falso.' },

        { id: 'm1_06', type: 'multiple',
          question: 'Qual é o valor de x após: x ← 10; x ← x + 5?',
          options: ['15', '10', '5', '105'],
          correct: 0,
          tip: 'x começa com 10, depois recebe 10 + 5 = 15.' },

        { id: 'm1_07', type: 'multiple',
          question: 'Qual afirmação sobre variáveis é verdadeira?',
          options: ['Seu valor pode mudar durante a execução', 'Seu valor nunca muda', 'Só podem armazenar números', 'Precisam ser declaradas com "var"'],
          correct: 0,
          tip: 'Variável = espaço na memória cujo valor pode ser alterado.' },

        { id: 'm1_08', type: 'multiple',
          question: 'O que é uma constante?',
          options: ['Um valor que não muda durante a execução', 'Uma variável do tipo Inteiro', 'Uma operação matemática', 'Um tipo de dado'],
          correct: 0,
          tip: 'Constante é definida uma vez e não pode ser alterada.' },

        { id: 'm1_09', type: 'multiple',
          question: 'Qual tipo de dado é mais adequado para "temperatura corporal"?',
          options: ['Real', 'Inteiro', 'Lógico', 'Texto'],
          correct: 0,
          tip: 'Temperatura pode ter casas decimais como 36.5 — use Real.' },

        { id: 'm1_10', type: 'multiple',
          question: 'Após: a ← 3; b ← a; a ← 10. Qual é o valor de b?',
          options: ['3', '10', '0', '13'],
          correct: 0,
          tip: 'b recebeu o valor de a no momento da atribuição (3). Mudar a depois não afeta b.' },

        { id: 'm1_11', type: 'multiple',
          question: 'Qual nome de variável é inválido?',
          options: ['2nome', 'nome2', 'meu_nome', 'nomeAluno'],
          correct: 0,
          tip: 'Nomes de variáveis não podem começar com número.' },

        { id: 'm1_12', type: 'multiple',
          question: 'O tipo Inteiro armazena:',
          options: ['Números sem casas decimais', 'Números com casas decimais', 'Palavras', 'Valores verdadeiro/falso'],
          correct: 0,
          tip: 'Inteiro: -3, 0, 7, 42. Sem ponto decimal.' },

        { id: 'm1_13', type: 'multiple',
          question: 'Qual é o resultado: x ← 5; y ← x; x ← 0. Qual é y?',
          options: ['5', '0', '50', 'indefinido'],
          correct: 0,
          tip: 'y recebeu 5 de x. Zerar x depois não afeta y.' },

        { id: 'm1_14', type: 'multiple',
          question: 'Para armazenar se uma lâmpada está ligada ou desligada, qual tipo usar?',
          options: ['Lógico', 'Inteiro', 'Texto', 'Real'],
          correct: 0,
          tip: 'Ligado/desligado = verdadeiro/falso = Lógico.' },

        { id: 'm1_15', type: 'multiple',
          question: 'O que significa declarar uma variável?',
          options: ['Reservar espaço na memória para armazenar um valor', 'Calcular um resultado', 'Exibir um valor na tela', 'Criar uma função'],
          correct: 0,
          tip: 'Declarar = dizer ao computador: reserve espaço com esse nome.' },

        { id: 'm1_16', type: 'multiple',
          question: 'Qual é o tipo de "falso"?',
          options: ['Lógico', 'Texto', 'Inteiro', 'Real'],
          correct: 0,
          tip: '"verdadeiro" e "falso" são valores do tipo Lógico.' },

        { id: 'm1_17', type: 'multiple',
          question: 'Qual operação é uma atribuição?',
          options: ['x ← 10', 'x == 10', 'x + 10', 'x > 10'],
          correct: 0,
          tip: '← é o operador de atribuição. == é comparação.' },

        { id: 'm1_18', type: 'multiple',
          question: 'Uma variável pode ter o mesmo nome que outra no mesmo escopo?',
          options: ['Não — causaria conflito', 'Sim, sem problema', 'Sim, se forem tipos diferentes', 'Apenas se uma for constante'],
          correct: 0,
          tip: 'Dois nomes iguais no mesmo escopo causam erro de redeclaração.' },

        { id: 'm1_19', type: 'multiple',
          question: 'Qual afirmação é falsa sobre tipos de dados?',
          options: ['Texto pode armazenar números para cálculo', 'Inteiro não tem casas decimais', 'Lógico tem dois valores possíveis', 'Real pode ter casas decimais'],
          correct: 0,
          tip: 'Texto "42" não pode ser usado em cálculo diretamente — precisaria de conversão.' },

        { id: 'm1_20', type: 'multiple',
          question: 'Após: nota ← 7.5. Qual tipo melhor descreve "nota"?',
          options: ['Real', 'Inteiro', 'Lógico', 'Texto'],
          correct: 0,
          tip: '7.5 tem casa decimal — tipo Real.' },

        { id: 'm1_21', type: 'write',
          context: 'Declare uma variável chamada "idade" e atribua o valor 20.',
          prompt: 'Use o formato: <code>variavel ← valor</code>',
          answers: ['idade ← 20', 'idade←20', 'idade <- 20', 'idade<-20', 'idade = 20'],
          tip: 'A seta ← significa "recebe". idade ← 20 significa que idade recebe o valor 20.',
          successMessage: 'Correto! Variável declarada e atribuída.' },

        { id: 'm1_22', type: 'write',
          context: 'Atribua o valor verdadeiro à variável "aprovado".',
          prompt: 'Use o formato: <code>variavel ← valor</code>',
          answers: ['aprovado ← verdadeiro', 'aprovado←verdadeiro', 'aprovado <- verdadeiro', 'aprovado = verdadeiro'],
          tip: 'Lógico recebe "verdadeiro" ou "falso" — sem aspas.',
          successMessage: 'Correto! Tipo Lógico atribuído.' },

        { id: 'm1_23', type: 'multiple',
          question: 'Qual é o resultado: x ← 2; x ← x * x?',
          options: ['4', '2', 'xx', '0'],
          correct: 0,
          tip: 'x começa com 2. x * x = 2 * 2 = 4.' },

        { id: 'm1_24', type: 'multiple',
          question: 'Por que usar nomes descritivos para variáveis?',
          options: ['Para o código ser legível e fácil de manter', 'Para economizar memória', 'Para o código rodar mais rápido', 'Para evitar erros de sintaxe'],
          correct: 0,
          tip: '"salarioMensal" é mais claro que "sm" ou "x".' },

        { id: 'm1_25', type: 'multiple',
          question: 'O que "inicializar" uma variável significa?',
          options: ['Atribuir um valor inicial a ela', 'Deletar a variável', 'Imprimir o valor dela', 'Mudar o tipo dela'],
          correct: 0,
          tip: 'Inicializar = dar o primeiro valor. Ex: contador ← 0.' },

        { id: 'm1_26', type: 'multiple',
          question: 'Qual é o tipo de dado mais adequado para o CPF "123.456.789-00"?',
          options: ['Texto', 'Inteiro', 'Real', 'Lógico'],
          correct: 0,
          tip: 'CPF tem pontos e hífen — não é número para cálculo. Use Texto.' },

        { id: 'm1_27', type: 'multiple',
          question: 'Após: a ← 1; b ← 2; a ← b; b ← a. Qual é b?',
          options: ['2', '1', '3', '0'],
          correct: 0,
          tip: 'a recebe 2. Depois b recebe o novo valor de a (2). b = 2.' },

        { id: 'm1_28', type: 'multiple',
          question: 'O que é tipo de dado?',
          options: ['A classificação do valor que uma variável pode armazenar', 'O nome da variável', 'O endereço de memória', 'O resultado de uma operação'],
          correct: 0,
          tip: 'Tipo define o que pode ser armazenado: número, texto, lógico.' },

        { id: 'm1_29', type: 'write',
          context: 'Troque os valores de duas variáveis "a" e "b" usando uma variável auxiliar "temp". Escreva apenas a linha que atribui b a temp.',
          prompt: 'Use: <code>temp ← ...</code>',
          answers: ['temp ← b', 'temp←b', 'temp <- b', 'temp = b'],
          tip: 'O primeiro passo da troca é salvar b em temp antes de sobrescrever.',
          successMessage: 'Correto! Primeiro passo da troca de variáveis.' },

        { id: 'm1_30', type: 'multiple',
          question: 'Qual é a diferença entre = e ← em pseudocódigo?',
          options: ['← é atribuição; = é comparação', '← é comparação; = é atribuição', 'São a mesma coisa', '← é para texto; = é para número'],
          correct: 0,
          tip: 'Em pseudocódigo: ← atribui valor. = compara. Não confunda!' },

        { id: 'm1_31', type: 'multiple',
          question: 'Uma variável do tipo Real pode receber um valor Inteiro?',
          options: ['Sim — 5 cabe em Real como 5.0', 'Não — tipos diferentes são incompatíveis', 'Só se converter explicitamente', 'Apenas se o inteiro for positivo'],
          correct: 0,
          tip: 'Real é mais abrangente que Inteiro. 5 vira 5.0 automaticamente.' },

        { id: 'm1_32', type: 'multiple',
          question: 'Qual é o valor de z: x ← 4; y ← 3; z ← x + y?',
          options: ['7', '43', '1', '12'],
          correct: 0,
          tip: 'z = 4 + 3 = 7. Simples adição.' },

        { id: 'm1_33', type: 'multiple',
          question: 'Por que variáveis precisam ser declaradas antes de usar?',
          options: ['Para o computador reservar espaço na memória', 'Para dar um tipo permanente', 'Para deixar o código mais bonito', 'Por convenção — não é obrigatório'],
          correct: 0,
          tip: 'Sem declaração, o computador não sabe onde guardar o valor.' },

        { id: 'm1_34', type: 'multiple',
          question: 'Qual dessas é uma variável do tipo Texto?',
          options: ['"Recife"', '3.14', 'verdadeiro', '42'],
          correct: 0,
          tip: 'Texto vem entre aspas duplas: "Recife".' },

        { id: 'm1_35', type: 'multiple',
          question: 'O que acontece com o valor anterior de uma variável quando ela recebe um novo valor?',
          options: ['É substituído e perdido', 'Fica armazenado em backup', 'É somado ao novo valor', 'Fica acessível pelo nome antigo'],
          correct: 0,
          tip: 'Atribuição sobrescreve. O valor anterior some.' },

        { id: 'm1_36', type: 'multiple',
          question: 'Qual tipo usar para "quantidade de filhos"?',
          options: ['Inteiro', 'Real', 'Texto', 'Lógico'],
          correct: 0,
          tip: 'Filhos são contados em números inteiros — 0, 1, 2, 3.' },

        { id: 'm1_37', type: 'multiple',
          question: 'Após: n ← 10; n ← n - 3; n ← n * 2. Qual é n?',
          options: ['14', '7', '20', '17'],
          correct: 0,
          tip: 'n=10 → n=10-3=7 → n=7*2=14.' },

        { id: 'm1_38', type: 'multiple',
          question: 'Qual é a finalidade de uma variável auxiliar?',
          options: ['Guardar temporariamente um valor durante uma operação', 'Ser exibida na tela', 'Armazenar o resultado final', 'Substituir todas as outras variáveis'],
          correct: 0,
          tip: 'Auxiliar é usada como rascunho — ex: troca de valores.' },

        { id: 'm1_39', type: 'multiple',
          question: 'O que "escopo" de uma variável significa?',
          options: ['A região do código onde ela existe e é acessível', 'O tipo de valor que ela armazena', 'A quantidade de memória que ocupa', 'O nome que ela recebe'],
          correct: 0,
          tip: 'Escopo define onde a variável "vive" no código.' },

        { id: 'm1_40', type: 'write',
          context: 'Uma loja tem 50 produtos em estoque. Declare "estoque" e atribua esse valor. Depois, escreva a linha que remove 8 produtos do estoque.',
          prompt: 'Escreva apenas a linha de atualização do estoque.',
          answers: ['estoque ← estoque - 8', 'estoque←estoque-8', 'estoque <- estoque - 8', 'estoque = estoque - 8'],
          tip: 'Para remover, subtraia do valor atual: estoque ← estoque - 8.',
          successMessage: 'Correto! Atualização de variável com base no valor atual.' },
    ],

    // ===== BLOCO M2 — Entrada e Saída (40 questões) =====
    bankM2: [
        { id: 'm2_01', type: 'multiple',
          question: 'Qual comando é usado para exibir informações na tela?',
          options: ['escrever()', 'ler()', 'imprimir()', 'mostrar()'],
          correct: 0,
          tip: 'escrever() exibe na tela. ler() captura do usuário.' },

        { id: 'm2_02', type: 'multiple',
          question: 'O que o comando ler() faz?',
          options: ['Captura um valor digitado pelo usuário', 'Exibe texto na tela', 'Calcula uma expressão', 'Cria uma variável'],
          correct: 0,
          tip: 'ler() pausa o programa e espera o usuário digitar algo.' },

        { id: 'm2_03', type: 'multiple',
          question: 'Qual é a saída de: escrever("Olá, mundo!")?',
          options: ['Olá, mundo!', '"Olá, mundo!"', 'Erro', 'Nada'],
          correct: 0,
          tip: 'As aspas delimitam o texto mas não aparecem na saída.' },

        { id: 'm2_04', type: 'multiple',
          question: 'Como exibir o valor de uma variável chamada "nome"?',
          options: ['escrever(nome)', 'escrever("nome")', 'ler(nome)', 'imprimir(nome)'],
          correct: 0,
          tip: 'Sem aspas = exibe o valor da variável. Com aspas = exibe a palavra "nome".' },

        { id: 'm2_05', type: 'multiple',
          question: 'O que acontece com: nome ← ler()?',
          options: ['O usuário digita e o valor vai para "nome"', 'Exibe o valor de nome', 'Cria a variável nome', 'Apaga o valor de nome'],
          correct: 0,
          tip: 'ler() captura a entrada e ← armazena em nome.' },

        { id: 'm2_06', type: 'multiple',
          question: 'Como exibir "Nota: " seguido do valor da variável "nota"?',
          options: ['escrever("Nota: ", nota)', 'escrever("Nota: " nota)', 'escrever(Nota: nota)', 'escrever("Nota: " + nota)'],
          correct: 0,
          tip: 'Texto e variável separados por vírgula dentro do escrever().' },

        { id: 'm2_07', type: 'multiple',
          question: 'Qual é a diferença entre escrever("x") e escrever(x)?',
          options: ['O primeiro exibe a letra x; o segundo exibe o valor da variável x', 'São iguais', 'O primeiro exibe o valor; o segundo exibe a letra', 'Ambos causam erro'],
          correct: 0,
          tip: 'Aspas = literal. Sem aspas = conteúdo da variável.' },

        { id: 'm2_08', type: 'multiple',
          question: 'Para que serve uma mensagem de prompt antes de ler()?',
          options: ['Para o usuário saber o que digitar', 'Para criar a variável', 'Para validar a entrada', 'Para formatar o texto'],
          correct: 0,
          tip: 'escrever("Digite sua idade: ") antes do ler() orienta o usuário.' },

        { id: 'm2_09', type: 'multiple',
          question: 'Qual seria a saída de:\nescrever("Resultado: ", 3 + 4)?',
          options: ['Resultado: 7', 'Resultado: 3 + 4', 'Resultado: 34', 'Erro'],
          correct: 0,
          tip: 'A expressão 3+4 é avaliada antes de exibir. Resultado: 7.' },

        { id: 'm2_10', type: 'multiple',
          question: 'O que é entrada de dados?',
          options: ['Informações fornecidas pelo usuário ao programa', 'Dados que o programa exibe', 'O código-fonte do programa', 'Variáveis declaradas no início'],
          correct: 0,
          tip: 'Entrada = o que entra no programa. Saída = o que sai (tela).' },

        { id: 'm2_11', type: 'multiple',
          question: 'Como ler dois valores em sequência para "a" e "b"?',
          options: ['a ← ler(); b ← ler()', 'ler(a, b)', 'a, b ← ler()', 'ler() → a, b'],
          correct: 0,
          tip: 'Cada ler() captura uma entrada. Use um por variável.' },

        { id: 'm2_12', type: 'multiple',
          question: 'Qual é a saída:\nnome ← "Ana"\nescrever("Olá, ", nome, "!")?',
          options: ['Olá, Ana!', 'Olá, nome!', '"Olá, Ana!"', 'Erro'],
          correct: 0,
          tip: 'nome contém "Ana". Concatenação: Olá, + Ana + ! = Olá, Ana!' },

        { id: 'm2_13', type: 'multiple',
          question: 'O que é saída de dados?',
          options: ['Informações que o programa exibe para o usuário', 'Dados que o programa recebe', 'Variáveis internas', 'Erros do programa'],
          correct: 0,
          tip: 'Saída = resultado que o programa mostra. Ex: escrever().' },

        { id: 'm2_14', type: 'multiple',
          question: 'O que acontece se ler() recebe "abc" mas a variável é do tipo Inteiro?',
          options: ['Erro de tipo', 'Armazena 0', 'Armazena "abc"', 'Ignora a entrada'],
          correct: 0,
          tip: 'Tipo incompatível gera erro. "abc" não é Inteiro.' },

        { id: 'm2_15', type: 'multiple',
          question: 'Qual é a saída:\nx ← 5\nescrever(x, " ao quadrado é ", x*x)?',
          options: ['5 ao quadrado é 25', '5 ao quadrado é x*x', 'x ao quadrado é 25', 'Erro'],
          correct: 0,
          tip: 'x=5, x*x=25. Saída: 5 ao quadrado é 25.' },

        { id: 'm2_16', type: 'multiple',
          question: 'Escrever("") exibe o quê?',
          options: ['Uma linha vazia', 'As aspas ""', 'Erro', 'Nada — é ignorado'],
          correct: 0,
          tip: 'String vazia exibe linha em branco.' },

        { id: 'm2_17', type: 'multiple',
          question: 'Como exibir o valor de "preco" com R$ na frente?',
          options: ['escrever("R$", preco)', 'escrever(R$ preco)', 'escrever("R$ preco")', 'escrever(R$, preco)'],
          correct: 0,
          tip: '"R$" é texto entre aspas, preco é a variável. Separe por vírgula.' },

        { id: 'm2_18', type: 'multiple',
          question: 'Qual a sequência correta para pedir e exibir a idade?',
          options: [
            'escrever("Idade: "); idade ← ler(); escrever("Você tem ", idade, " anos")',
            'idade ← ler(); escrever("Idade: "); escrever(idade)',
            'escrever(idade); idade ← ler()',
            'ler("Idade: "); escrever(idade)'
          ],
          correct: 0,
          tip: 'Ordem: prompt → ler → exibir resultado.' },

        { id: 'm2_19', type: 'multiple',
          question: 'O que a vírgula faz dentro de escrever()?',
          options: ['Separa múltiplos valores a exibir', 'Cria nova linha', 'É obrigatória sempre', 'Separa decimais'],
          correct: 0,
          tip: 'escrever("a", "b") exibe "ab" — a vírgula une sem espaço extra.' },

        { id: 'm2_20', type: 'multiple',
          question: 'Qual é a saída:\na ← 3; b ← 7\nescrever(a + b, " é a soma")?',
          options: ['10 é a soma', '3 + 7 é a soma', 'a + b é a soma', 'Erro'],
          correct: 0,
          tip: 'a+b é avaliado primeiro: 3+7=10. Saída: 10 é a soma.' },

        { id: 'm2_21', type: 'write',
          context: 'Escreva o comando para exibir a mensagem: Bem-vindo ao sistema!',
          prompt: 'Use <code>escrever()</code>',
          answers: ['escrever("Bem-vindo ao sistema!")', 'escrever( "Bem-vindo ao sistema!" )'],
          tip: 'Texto literal vai entre aspas duplas dentro do escrever().',
          successMessage: 'Correto! Saída de texto literal.' },

        { id: 'm2_22', type: 'write',
          context: 'O usuário digitou seu nome. A variável é "nomeUsuario". Exiba: Olá, [nome]!',
          prompt: 'Use <code>escrever()</code> com texto e variável',
          answers: ['escrever("Olá, ", nomeUsuario, "!")', 'escrever("Olá, ",nomeUsuario,"!")'],
          tip: 'Misture texto entre aspas e variáveis separados por vírgula.',
          successMessage: 'Correto! Concatenação de texto e variável.' },

        { id: 'm2_23', type: 'multiple',
          question: 'Qual é a saída:\nescrever("5 + 3 =", 5 + 3)?',
          options: ['5 + 3 = 8', '5 + 3 = 5 + 3', '"5 + 3 = 8"', 'Erro'],
          correct: 0,
          tip: '"5 + 3 =" é texto literal. 5+3 é expressão avaliada (8).' },

        { id: 'm2_24', type: 'multiple',
          question: 'Um programa recebe dois números e exibe a média. Qual é a última instrução?',
          options: ['escrever("Média: ", media)', 'media ← ler()', 'media ← (a + b) / 2', 'escrever(a, b)'],
          correct: 0,
          tip: 'A última instrução sempre exibe o resultado calculado.' },

        { id: 'm2_25', type: 'multiple',
          question: 'Para separar saídas em linhas diferentes, o que usar?',
          options: ['Um escrever() por linha', 'Vírgulas no mesmo escrever()', 'Ponto e vírgula', 'Dois-pontos'],
          correct: 0,
          tip: 'Cada escrever() gera uma nova linha na saída.' },

        { id: 'm2_26', type: 'multiple',
          question: 'O que a instrução ler() retorna?',
          options: ['O valor digitado pelo usuário', 'Sempre uma string', 'O tipo da variável', 'Nada'],
          correct: 0,
          tip: 'ler() retorna o que o usuário digitou, no tipo correto da variável.' },

        { id: 'm2_27', type: 'multiple',
          question: 'Qual é a ordem correta de um programa simples de cálculo?',
          options: ['Ler entradas → Calcular → Exibir resultado', 'Exibir → Calcular → Ler', 'Calcular → Ler → Exibir', 'Ler → Exibir → Calcular'],
          correct: 0,
          tip: 'IPO: Input (ler) → Processing (calcular) → Output (exibir).' },

        { id: 'm2_28', type: 'multiple',
          question: 'Como exibir apenas o número 42 na tela?',
          options: ['escrever(42)', 'escrever("42")', 'Ambos funcionam', 'ler(42)'],
          correct: 2,
          tip: 'escrever(42) exibe o número. escrever("42") exibe o texto. Ambos mostram 42.' },

        { id: 'm2_29', type: 'multiple',
          question: 'Qual erro está no código:\nescrever(nome)\nnome ← ler()?',
          options: ['Usa nome antes de ler', 'escrever está errado', 'ler está errado', 'Nenhum erro'],
          correct: 0,
          tip: 'nome não tem valor ainda quando escrever é chamado.' },

        { id: 'm2_30', type: 'multiple',
          question: 'O que é um prompt de entrada?',
          options: ['Mensagem que instrui o usuário a digitar algo', 'Comando que lê a entrada', 'Variável de entrada', 'Tipo de dado especial'],
          correct: 0,
          tip: 'Prompt = aviso amigável. Ex: escrever("Digite seu nome: ").' },

        { id: 'm2_31', type: 'write',
          context: 'Escreva o comando para ler um valor do usuário e armazenar em "altura".',
          prompt: 'Use <code>altura ← ler()</code>',
          answers: ['altura ← ler()', 'altura←ler()', 'altura <- ler()', 'altura = ler()'],
          tip: 'ler() captura a entrada. ← armazena na variável.',
          successMessage: 'Correto! Leitura de entrada do usuário.' },

        { id: 'm2_32', type: 'multiple',
          question: 'Qual é a saída:\nproduto ← "Notebook"\npreco ← 2500\nescrever(produto, ": R$", preco)?',
          options: ['Notebook: R$2500', 'produto: R$preco', '"Notebook: R$2500"', 'Erro'],
          correct: 0,
          tip: 'produto = "Notebook", preco = 2500. Concatenação direta.' },

        { id: 'm2_33', type: 'multiple',
          question: 'Para que serve comentários no código?',
          options: ['Explicar o que o código faz para humanos', 'Acelerar a execução', 'Criar variáveis invisíveis', 'Substituir escrever()'],
          correct: 0,
          tip: 'Comentários (// texto) são ignorados pelo computador, úteis para humanos.' },

        { id: 'm2_34', type: 'multiple',
          question: 'O que acontece se esquecer as aspas: escrever(Olá)?',
          options: ['Erro — Olá é tratado como variável não declarada', 'Exibe Olá normalmente', 'Exibe vazio', 'Exibe "Olá"'],
          correct: 0,
          tip: 'Sem aspas, Olá vira nome de variável. Se não declarada, erro.' },

        { id: 'm2_35', type: 'multiple',
          question: 'Qual é a saída:\na ← 10; b ← 3\nescrever(a, " dividido por ", b, " = ", a/b)?',
          options: ['10 dividido por 3 = 3.33...', '10 dividido por 3 = 3', 'a dividido por b = a/b', 'Erro'],
          correct: 0,
          tip: '10/3 = 3.333... (Real). A expressão é avaliada.' },

        { id: 'm2_36', type: 'multiple',
          question: 'Como exibir uma linha separadora de hífens?',
          options: ['escrever("----------")', 'escrever(----------)', 'separador()', 'linha()'],
          correct: 0,
          tip: 'Qualquer texto pode ser exibido, incluindo sequências de caracteres.' },

        { id: 'm2_37', type: 'multiple',
          question: 'Qual a diferença entre entrada e saída no contexto de programação?',
          options: ['Entrada vem do usuário; saída vai para o usuário', 'São a mesma coisa', 'Entrada é código; saída é dado', 'Saída vem do usuário; entrada vai para o usuário'],
          correct: 0,
          tip: 'INPUT → programa → OUTPUT. Usuário fornece entrada, recebe saída.' },

        { id: 'm2_38', type: 'multiple',
          question: 'Qual seria a saída:\nn ← 5\nescrever("O dobro de ", n, " é ", n*2)?',
          options: ['O dobro de 5 é 10', 'O dobro de n é n*2', 'O dobro de 5 é n*2', 'Erro'],
          correct: 0,
          tip: 'n=5, n*2=10. Texto literal + variáveis avaliadas.' },

        { id: 'm2_39', type: 'multiple',
          question: 'Em qual situação usar ler() é necessário?',
          options: ['Quando o valor depende do usuário em tempo de execução', 'Sempre que declarar variável', 'Quando calcular expressões', 'Quando exibir resultados'],
          correct: 0,
          tip: 'ler() é para dados dinâmicos que variam por usuário ou execução.' },

        { id: 'm2_40', type: 'write',
          context: 'Exiba o resultado da divisão de "total" por "pessoas", com o texto "Cada um paga: R$" na frente.',
          prompt: 'Use <code>escrever()</code> com texto e expressão',
          answers: [
            'escrever("Cada um paga: R$", total/pessoas)',
            'escrever("Cada um paga: R$",total/pessoas)',
            'escrever("Cada um paga: R$", total / pessoas)'
          ],
          tip: 'Texto entre aspas + vírgula + expressão matemática.',
          successMessage: 'Correto! Saída com expressão calculada.' },
    ],

    // ===== BLOCO M3 — Operadores (40 questões) =====
    bankM3: [
        { id: 'm3_01', type: 'multiple',
          question: 'Qual é o resultado de 10 % 3?',
          options: ['1', '3', '0', '7'],
          correct: 0,
          tip: '% retorna o resto da divisão. 10 ÷ 3 = 3 com resto 1.' },

        { id: 'm3_02', type: 'multiple',
          question: 'Qual operador verifica se dois valores são IGUAIS?',
          options: ['==', '=', '!=', '>='],
          correct: 0,
          tip: '== compara. = atribui. Não confunda!' },

        { id: 'm3_03', type: 'multiple',
          question: 'O que retorna: 5 > 3 E 2 < 4?',
          options: ['verdadeiro', 'falso', '5', 'erro'],
          correct: 0,
          tip: '5>3 é verdadeiro E 2<4 é verdadeiro. V E V = verdadeiro.' },

        { id: 'm3_04', type: 'multiple',
          question: 'O que retorna: 5 > 10 OU 3 == 3?',
          options: ['verdadeiro', 'falso', '3', 'erro'],
          correct: 0,
          tip: '5>10 é falso. 3==3 é verdadeiro. F OU V = verdadeiro.' },

        { id: 'm3_05', type: 'multiple',
          question: 'O que retorna: NÃO verdadeiro?',
          options: ['falso', 'verdadeiro', '0', 'erro'],
          correct: 0,
          tip: 'NÃO inverte. NÃO verdadeiro = falso.' },

        { id: 'm3_06', type: 'multiple',
          question: 'Qual é o resultado de 2 + 3 * 4?',
          options: ['14', '20', '24', '9'],
          correct: 0,
          tip: 'Multiplicação antes da adição: 3*4=12, 2+12=14.' },

        { id: 'm3_07', type: 'multiple',
          question: 'Qual é o resultado de (2 + 3) * 4?',
          options: ['20', '14', '24', '10'],
          correct: 0,
          tip: 'Parênteses primeiro: 2+3=5, 5*4=20.' },

        { id: 'm3_08', type: 'multiple',
          question: 'O que retorna: 8 % 2?',
          options: ['0', '4', '1', '2'],
          correct: 0,
          tip: '8 ÷ 2 = 4 exato, sem resto. Resto = 0.' },

        { id: 'm3_09', type: 'multiple',
          question: 'Um número é par quando:',
          options: ['numero % 2 == 0', 'numero / 2 == 0', 'numero % 2 == 1', 'numero == 2'],
          correct: 0,
          tip: 'Par = divisível por 2 sem resto. Resto 0 = par.' },

        { id: 'm3_10', type: 'multiple',
          question: 'Qual é o resultado: NÃO (5 > 3)?',
          options: ['falso', 'verdadeiro', '5', 'erro'],
          correct: 0,
          tip: '5>3 é verdadeiro. NÃO verdadeiro = falso.' },

        { id: 'm3_11', type: 'multiple',
          question: 'O que retorna: falso E verdadeiro?',
          options: ['falso', 'verdadeiro', 'nulo', 'erro'],
          correct: 0,
          tip: 'E exige ambos verdadeiros. F E V = falso.' },

        { id: 'm3_12', type: 'multiple',
          question: 'O que retorna: falso OU falso?',
          options: ['falso', 'verdadeiro', 'nulo', 'erro'],
          correct: 0,
          tip: 'OU precisa de pelo menos um verdadeiro. F OU F = falso.' },

        { id: 'm3_13', type: 'multiple',
          question: 'Qual expressão verifica se x está entre 1 e 10?',
          options: ['x >= 1 E x <= 10', 'x > 1 OU x < 10', '1 < x < 10', 'x == 1 E x == 10'],
          correct: 0,
          tip: 'Para intervalo use E: x >= 1 E x <= 10.' },

        { id: 'm3_14', type: 'multiple',
          question: 'Qual é o resultado: 15 / 4 (divisão inteira)?',
          options: ['3', '3.75', '4', '1'],
          correct: 0,
          tip: 'Divisão inteira descarta o decimal. 15 ÷ 4 = 3 (resto 3).' },

        { id: 'm3_15', type: 'multiple',
          question: 'O que a precedência de operadores define?',
          options: ['A ordem em que as operações são executadas', 'O tipo do resultado', 'A velocidade do cálculo', 'O número de operandos'],
          correct: 0,
          tip: 'Precedência = ordem de execução. Parênteses > * / % > + -.' },

        { id: 'm3_16', type: 'multiple',
          question: 'Qual operador tem maior precedência?',
          options: ['*', '+', 'E', 'OU'],
          correct: 0,
          tip: 'Aritméticos > Relacionais > Lógicos. Entre aritméticos: * antes de +.' },

        { id: 'm3_17', type: 'multiple',
          question: 'Qual é o resultado: 10 != 10?',
          options: ['falso', 'verdadeiro', '0', 'erro'],
          correct: 0,
          tip: '!= significa diferente. 10 é igual a 10, então != retorna falso.' },

        { id: 'm3_18', type: 'multiple',
          question: 'O que retorna: verdadeiro E verdadeiro E falso?',
          options: ['falso', 'verdadeiro', 'erro', 'indefinido'],
          correct: 0,
          tip: 'V E V = V, depois V E F = falso. Qualquer falso contamina o E.' },

        { id: 'm3_19', type: 'multiple',
          question: 'Para verificar se um ano é bissexto (divisível por 4), qual expressão usar?',
          options: ['ano % 4 == 0', 'ano / 4 == 0', 'ano % 4 != 0', 'ano == 4'],
          correct: 0,
          tip: 'Divisível por 4 = resto 0. ano % 4 == 0.' },

        { id: 'm3_20', type: 'multiple',
          question: 'Qual é o resultado de: x ← 5; y ← x >= 5?',
          options: ['y = verdadeiro', 'y = 5', 'y = falso', 'erro'],
          correct: 0,
          tip: '5 >= 5 é verdadeiro. y recebe verdadeiro (tipo Lógico).' },

        { id: 'm3_21', type: 'multiple',
          question: 'Qual é a saída:\nx ← 10; y ← 3\nescrever(x % y)?',
          options: ['1', '3', '0', '3.33'],
          correct: 0,
          tip: '10 ÷ 3 = 3, resto 1. % retorna o resto.' },

        { id: 'm3_22', type: 'multiple',
          question: 'O operador >= significa:',
          options: ['maior ou igual', 'maior que', 'diferente de', 'igual a'],
          correct: 0,
          tip: '>= é "maior ou igual a". 5 >= 5 é verdadeiro.' },

        { id: 'm3_23', type: 'multiple',
          question: 'Para um funcionário receber hora extra se trabalhou MAIS de 8h E tem chefia aprovada:',
          options: ['horas > 8 E aprovado == verdadeiro', 'horas > 8 OU aprovado == verdadeiro', 'horas >= 8 E aprovado', 'horas > 8'],
          correct: 0,
          tip: 'Ambas condições precisam ser verdadeiras — use E.' },

        { id: 'm3_24', type: 'multiple',
          question: 'Qual é o resultado: 2 ** 3 (potência)?',
          options: ['8', '6', '9', '5'],
          correct: 0,
          tip: '2³ = 2 × 2 × 2 = 8.' },

        { id: 'm3_25', type: 'multiple',
          question: 'NÃO falso retorna:',
          options: ['verdadeiro', 'falso', '1', 'erro'],
          correct: 0,
          tip: 'NÃO inverte. NÃO falso = verdadeiro.' },

        { id: 'm3_26', type: 'multiple',
          question: 'Qual expressão verifica se um número NÃO é zero?',
          options: ['numero != 0', 'numero == 0', 'NÃO numero', 'numero > 0'],
          correct: 0,
          tip: '!= significa diferente de. numero != 0 = número não é zero.' },

        { id: 'm3_27', type: 'multiple',
          question: 'Qual é o resultado: (verdadeiro OU falso) E falso?',
          options: ['falso', 'verdadeiro', 'erro', 'indefinido'],
          correct: 0,
          tip: 'Parênteses primeiro: V OU F = V. Depois: V E F = falso.' },

        { id: 'm3_28', type: 'multiple',
          question: 'Um aluno passa se nota >= 6 OU frequência >= 75. Qual expressão?',
          options: ['nota >= 6 OU frequencia >= 75', 'nota >= 6 E frequencia >= 75', 'nota > 6 OU frequencia > 75', 'nota >= 6 E frequencia > 75'],
          correct: 0,
          tip: '"ou" no enunciado = operador OU. Basta uma condição verdadeira.' },

        { id: 'm3_29', type: 'write',
          context: 'Escreva a expressão que verifica se um número é ímpar.',
          prompt: 'Use a variável <code>numero</code>',
          answers: ['numero % 2 != 0', 'numero%2!=0', 'numero % 2 == 1', 'numero%2==1'],
          tip: 'Ímpar = resto diferente de zero. numero % 2 != 0.',
          successMessage: 'Correto! Módulo para verificar paridade.' },

        { id: 'm3_30', type: 'multiple',
          question: 'Qual é o resultado: 100 % 10?',
          options: ['0', '10', '1', '100'],
          correct: 0,
          tip: '100 ÷ 10 = 10 exato, sem resto. % retorna 0.' },

        { id: 'm3_31', type: 'multiple',
          question: 'Para verificar se x é positivo E par:',
          options: ['x > 0 E x % 2 == 0', 'x > 0 OU x % 2 == 0', 'x >= 0 E x % 2 == 0', 'x > 0 E x % 2 != 0'],
          correct: 0,
          tip: 'Positivo: x > 0. Par: x % 2 == 0. Ambos com E.' },

        { id: 'm3_32', type: 'multiple',
          question: 'Qual operador tem MENOR precedência entre os lógicos?',
          options: ['OU', 'E', 'NÃO', 'Todos iguais'],
          correct: 0,
          tip: 'Precedência lógica: NÃO > E > OU. OU é avaliado por último.' },

        { id: 'm3_33', type: 'multiple',
          question: 'Qual é o resultado: NÃO (falso E verdadeiro)?',
          options: ['verdadeiro', 'falso', 'erro', 'indefinido'],
          correct: 0,
          tip: 'Parênteses: F E V = falso. NÃO falso = verdadeiro.' },

        { id: 'm3_34', type: 'multiple',
          question: 'O que = e == têm em comum?',
          options: ['Ambos envolvem igualdade, mas com propósitos diferentes', 'São sinônimos', 'Ambos comparam valores', 'Ambos atribuem valores'],
          correct: 0,
          tip: '= atribui. == compara. Parecidos mas completamente diferentes.' },

        { id: 'm3_35', type: 'multiple',
          question: 'Qual é o resultado: 7 % 7?',
          options: ['0', '1', '7', '49'],
          correct: 0,
          tip: '7 ÷ 7 = 1 exato. Resto = 0.' },

        { id: 'm3_36', type: 'multiple',
          question: 'Para um desconto ser aplicado se o cliente é VIP OU compra > 500:',
          options: ['vip == verdadeiro OU compra > 500', 'vip == verdadeiro E compra > 500', 'vip OU compra >= 500', 'vip E compra > 500'],
          correct: 0,
          tip: '"ou" no enunciado = operador OU. Uma condição basta.' },

        { id: 'm3_37', type: 'write',
          context: 'Escreva a expressão que verifica se "x" é diferente de "y".',
          prompt: 'Use os operadores relacionais',
          answers: ['x != y', 'x!=y', 'x <> y', 'x<>y'],
          tip: '!= significa "diferente de".',
          successMessage: 'Correto! Operador de diferença.' },

        { id: 'm3_38', type: 'multiple',
          question: 'Qual é o resultado: verdadeiro OU verdadeiro OU falso?',
          options: ['verdadeiro', 'falso', 'erro', 'indefinido'],
          correct: 0,
          tip: 'OU só precisa de um verdadeiro. V OU V = V, V OU F = V.' },

        { id: 'm3_39', type: 'multiple',
          question: 'Qual expressão representa "x é múltiplo de 5"?',
          options: ['x % 5 == 0', 'x / 5 == 0', 'x % 5 != 0', 'x == 5'],
          correct: 0,
          tip: 'Múltiplo = divisível sem resto. x % 5 == 0.' },

        { id: 'm3_40', type: 'write',
          context: 'Um sistema libera acesso se o usuário tem nível >= 3 E está ativo. Escreva a condição completa.',
          prompt: 'Use as variáveis <code>nivel</code> e <code>ativo</code>',
          answers: [
            'nivel >= 3 E ativo == verdadeiro',
            'nivel>=3 E ativo==verdadeiro',
            'nivel >= 3 E ativo',
            'nivel>=3 E ativo'
          ],
          tip: 'Duas condições com E. "ativo" sozinho já representa verdadeiro.',
          successMessage: 'Correto! Condição composta com E.' },
    ]
};
